name: Changelog CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
